msgid ""
msgstr ""
"Project-Id-Version: BackupSuite\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-07-22 19:19+0200\n"
"PO-Revision-Date: \n"
"Last-Translator: Gringo <openpli@tiscali.it>\n"
"Language-Team: \n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Poedit-SourceCharset: UTF-8\n"
"X-Generator: Poedit 2.1.1\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"X-Poedit-Basepath: ../../..\n"
"X-Poedit-SearchPath-0: .\n"

#: ../plugin.py:441
msgid ""
"\n"
"The found files:"
msgstr ""
"\n"
"File trovati:"

#: ../plugin.py:358
msgid ""
"\n"
"You are using dual multiboot!"
msgstr ""
"\n"
"Si sta usando il dual multiboot!"

#: ../plugin.py:447
#, python-format
msgid "  %s (maybe error)"
msgstr " %s (possibile errore)"

#: ../plugin.py:444
#, python-format
msgid "  %s (maybe ok)"
msgstr " %s (possibile OK)"

#: ../message.py:180
msgid " MB available space"
msgstr "Spazio libero (MB)"

#: ../message.py:185
msgid " MB needed space"
msgstr "Spazio necessario (MB)"

#: ../plugin.py:450
msgid " nothing!"
msgstr "Niente!"

#: ../message.py:45
msgid " size to be backed up: "
msgstr " dimensione del backup: "

#: ../message.py:175
msgid " to make a back-up!"
msgstr " per effettuare un backup!"

#: ../message.py:169
msgid "* * * WARNING * * *"
msgstr "* * * ATTENZIONE * * *"

#: ../plugin.py:480
msgid "A recording is currently running. Please stop the recording before trying to start a flashing."
msgstr "Una registrazione è in corso. Si prega di fermare la registrazione prima di iniziare il flashing."

#: ../message.py:70
msgid "Additional backup -> "
msgstr "Altri backup -> "

#: ../message.py:35
msgid "BACK-UP TOOL, FOR MAKING A COMPLETE BACK-UP"
msgstr "STRUMENTO DI BACKUP, PER  ESEGUIRE UN BACKUP COMPLETO"

#: ../plugin.py:132
msgid "Backup > HDD"
msgstr "Backup > HDD"

#: ../plugin.py:130
#, fuzzy
msgid "Backup > MMC"
msgstr "Backup > HDD"

#: ../plugin.py:133
msgid "Backup > USB"
msgstr "Backup > USB"

#: ../plugin.py:584 ../plugin.py:591
msgid "Backup and restore your image"
msgstr ""

#: ../message.py:149
msgid "Backup done with: "
msgstr "Backup effettuato con: "

#: ../message.py:106
msgid "Backup finished and copied to your USB-flashdrive."
msgstr "Il Backup è finito e sarà copiato nella chiavetta USB."

#: ../plugin.py:338 ../plugin.py:541
msgid "Backup info"
msgstr "Info Backup"

#: ../plugin.py:583 ../plugin.py:590
msgid "BackupSuite"
msgstr "BackupSuite"

#: ../plugin.py:131 ../plugin.py:233 ../plugin.py:262
msgid "Close"
msgstr "Chiudere"

#: ../message.py:65
msgid "Create: kerneldump"
msgstr "Creando: Kerneldump"

#: ../message.py:60
msgid "Create: root.ubifs"
msgstr "Creando: root.ubifs"

#: ../plugin.py:339 ../plugin.py:570
msgid "Delete"
msgstr "Eliminare"

#: ../plugin.py:567
msgid "Delete backup"
msgstr "Eliminare Backup"

#: ../plugin.py:540
#, python-format
msgid "Do you really want to unpack %s ?"
msgstr "Si desidera veramente scompattare %s  ?"

#: ../plugin.py:153
msgid ""
"Do you want to make a back-up on USB?\n"
"\n"
"This only takes a few minutes depending on the used filesystem and is fully automatic.\n"
"\n"
"Make sure you first insert an USB flash drive before you select Yes."
msgstr ""
"Si desidera fare un backup su USB?\n"
"\n"
"Questa operazione richiede pochi minuti a seconda del file system utilizzato ed è completamente automatica.\n"
"\n"
"Assicuratevi che la chiavetta USB sia inserita prima di selezionare Sì."

#: ../plugin.py:150
msgid ""
"Do you want to make an USB-back-up image on HDD? \n"
"\n"
"This only takes a few minutes and is fully automatic.\n"
msgstr ""
"Si desidera fare un'immagine USB di backup sul disco rigido?\n"
"\n"
"Questa operazione richiede pochi minuti ed è completamente automatica. \n"

#: ../plugin.py:156
#, fuzzy
msgid ""
"Do you want to make an USB-back-up image on MMC? \n"
"\n"
"This only takes a few minutes and is fully automatic.\n"
msgstr ""
"Si desidera fare un'immagine USB di backup sul disco rigido?\n"
"\n"
"Questa operazione richiede pochi minuti ed è completamente automatica. \n"

#: ../plugin.py:470
msgid "Exit"
msgstr "Uscire"

#: ../plugin.py:484
msgid "Flashing: "
msgstr "Flashing:"

#: ../plugin.py:369
msgid "For flashing your receiver files are needed:\n"
msgstr "Per eseguire un flash del ricevitore è necessario il file:\n"

# #: message22
#: ../message.py:129
msgid "Full back-up direct to USB"
msgstr "Backup completo su USB"

#: ../plugin.py:194
msgid "Full back-up on HDD"
msgstr "Backup completo su disco rigido"

#: ../plugin.py:208
#, fuzzy
msgid "Full back-up on MMC"
msgstr "Backup completo su disco rigido"

#: ../plugin.py:201
msgid "Full back-up to USB"
msgstr "Backup completo su USB"

#: ../message.py:235
#, fuzzy
msgid "Full back-up to the MultiMediaCard"
msgstr "Backup completo su disco rigido"

#: ../message.py:111
msgid "Full back-up to the harddisk"
msgstr "Backup completo su disco rigido"

#: ../message.py:123
msgid "If you place an USB-stick containing this file then the back-up will be automatically made onto the USB-stick and can be used to restore the current image if necessary."
msgstr "Se la chiavetta USB contiene questo file allora un backup sarà automaticamente creato sulla chiavetta USB e potrà essere usato per ripristinare l'attuale immagine se necessario."

#: ../message.py:90
msgid "Image creation FAILED!"
msgstr "Creazione dell'immagine FALLITA!"

#: ../message.py:225
msgid "Installed packages contained in this backup:"
msgstr "Pacchetti installati contenuti in questo backup:"

#: ../message.py:154
msgid "KB per second"
msgstr "KB per secondi"

#: ../plugin.py:127
msgid "Make a backup or restore a backup"
msgstr "Eseguire o ripristinare un backup"

#: ../message.py:159
msgid "Most likely this back-up can't be restored because of it's size, it's simply too big to restore. This is a limitation of the bootloader not of the back-up or the BackupSuite."
msgstr "Probabilmente il backup non può essere ripristinato perché la dimensione è semplicemente troppo grande per essere ripristinata. Questa è una limitazione del bootloader e non del backup o di BackupSuite."

#: ../plugin.py:45
msgid "NAS"
msgstr "NAS"

#: ../message.py:230
msgid "NFI Image created in: "
msgstr "Immagine NFI creata in:"

#: ../plugin.py:516
msgid "NOT found files for flashing!\n"
msgstr "File per il flash non trovati!\n"

#: ../message.py:220
msgid "No additional USB-stick found to copy an extra backup"
msgstr "Nessuna chiavetta USB aggiuntiva trovata per copiare un backup extra"

#: ../plugin.py:173 ../message.py:30
msgid "No supported receiver found!"
msgstr "Non è stato trovato nessun ricevitore supportato!"

#: ../message.py:170
msgid "Not enough free space on "
msgstr "Non c'è abbastanza spazio libero "

#: ../plugin.py:458 ../plugin.py:499
msgid "Only kernel"
msgstr "Solo kernel"

#: ../plugin.py:457 ../plugin.py:496
msgid "Only root"
msgstr "Solo root"

#: ../message.py:118
msgid "PLEASE READ THIS:"
msgstr "LEGGERE PRIMA:"

#: ../message.py:40
msgid "Please be patient, a backup will now be made, this will take about: "
msgstr "Si prega di essere pazienti, un backup sarà eseguito e impiegherà circa: "

#: ../message.py:85
msgid "Please check the manual of the receiver on how to restore the image."
msgstr "Controllare nel manuale del ricevitore come ripristinare l'immagine."

#: ../plugin.py:234
msgid "Please wait"
msgstr "Attendere prego..."

#: ../plugin.py:528
msgid "Please: DO NOT reboot your STB and turn off the power.\n"
msgstr "Attenzione: NON eseguire un riavvio o spegnere il ricevitore !\n"

#: ../message.py:215
msgid "Probably you are trying to make the back-up in flash memory"
msgstr "Probabilmente si sta tentando a fare il backup nella memoria flash"

#: ../plugin.py:134
msgid "Restore backup"
msgstr "Ripristinare backup"

#: ../plugin.py:336 ../plugin.py:353 ../plugin.py:362
msgid "Run flash"
msgstr "Iniziare il Flash"

#: ../plugin.py:464 ../plugin.py:511
msgid "Second partition (only kernel)"
msgstr "Seconda partizione (solo kernel)"

#: ../plugin.py:463 ../plugin.py:508
msgid "Second partition (only root)"
msgstr "Seconda partizione (solo root)"

#: ../plugin.py:462 ../plugin.py:505
msgid "Second partition (root and kernel)"
msgstr "Seconda partizione (root e kernel)"

#: ../plugin.py:368
msgid "Select parameter for start flash!\n"
msgstr "Selezionare i parametri per iniziare il flash!\n"

#: ../plugin.py:261
msgid "Select the folder with backup"
msgstr "Selezionare la cartella con backup"

#: ../plugin.py:521
msgid "Show only found image and mtd partitions.\n"
msgstr "Mostrare solo le immagini trovate e la partizione MTD.\n"

#: ../plugin.py:455 ../plugin.py:487
msgid "Simulate (no write)"
msgstr "Simulazione (non esecuzione)"

#: ../plugin.py:461 ../plugin.py:502
msgid "Simulate second partition (no write)"
msgstr "Simula seconda partizione (nessuna scrittura)"

#: ../message.py:55
msgid "Some information about the task"
msgstr "Alcune informazioni sul processo "

#: ../plugin.py:456 ../plugin.py:490
msgid "Standard (root and kernel)"
msgstr "Standard (root e kernel)"

#: ../message.py:134
msgid "The content of the folder is:"
msgstr "Il contenuto della cartella è:"

#: ../plugin.py:529
msgid "The image or kernel will be flashing and auto booted in few minutes.\n"
msgstr "L'immagine o il kernel sarà flashato e automaticamente avviato in alcuni minuti\n"

#: ../message.py:190
msgid "The program will abort, please try another medium with more free space to create your back-up."
msgstr "Il programma sarà terminato, usare un'altra unità che abbia più spazio per creare il vostro backup."

#: ../message.py:124
msgid "The program will exit now."
msgstr "Il programma terminerà ora."

#: ../message.py:164
msgid "There COULD be a problem with restoring this back-up because the size of the back-up comes close to the maximum size. This is a limitation of the bootloader not of the back-up or the BackupSuite."
msgstr "E' possibile che ci sia un problema nel ripristino dell'immagine poiché la dimensione del backup è vicina alla dimensione massima. Questa è una limitazione del bootloader e non del backup o di  BackupSuite."

#: ../message.py:116
msgid "There is NO valid USB-stick found, so I've got nothing to do."
msgstr "Non esiste una chiavetta USB valida, non è possibile fare niente."

#: ../message.py:100
msgid "There is a valid USB-flashdrive detected in one of the USB-ports, therefore an extra copy of the back-up image will now be copied to that USB-flashdrive."
msgstr "E' presente una chiavetta USB in una delle porte disponibili, per questo motivo un'altra copia dell'immagine sarà creata nella chiavetta USB."

#: ../message.py:101
msgid "This only takes about 20 seconds....."
msgstr "Impiegherà circa 20 secondi....."

#: ../message.py:139
msgid "Time required for this process: "
msgstr "Tempo richiesto per questo processo: "

#: ../message.py:119
msgid "To back-up directly to the USB-stick, the USB-stick MUST contain a file with the name:"
msgstr "Per effettuare un backup completo su chiavetta USB è necessario creare un file con questo nome:"

#: ../message.py:75
msgid "USB Image created in: "
msgstr "Immagine USB creata in: "

#: ../plugin.py:334 ../plugin.py:537
msgid "Unzip"
msgstr "Scompattare "

#: ../message.py:200
msgid "Using your own custom lookuptable.txt from the folder /etc"
msgstr "Usando il tuo lookuptable.txt personalizzato dalla cartella /etc"

#: ../message.py:205
msgid "Version unknown, probably not installed the right way."
msgstr "Versione sconosciuta, probabilmente non è installata nel modo giusto."

#: ../plugin.py:359
msgid ""
"Warning!\n"
"Use at your own risk! Make always a backup before use!\n"
"Don't use it if you use multiple ubi volumes in ubi layer!"
msgstr ""
"Attenzione !\n"
"!!! Usare a proprio rischio !!! Eseguire sempre un backup prima di usare!\n"
"Non usare con volumi ubi multipli in ubi layer!"

#: ../plugin.py:232
msgid "What is new since the last release?"
msgstr "Novità rispetto all'ultima versione?"

#: ../plugin.py:571
#, python-format
msgid ""
"You are about to delete this backup:\n"
"\n"
"%s\n"
"Continue?"
msgstr ""
"Si sta per eliminare questo backup:\n"
"\n"
"%s\n"
"Continuare?"

#: ../plugin.py:527
msgid "Your STB will freeze during the flashing process.\n"
msgstr "Il ricevitore si fermerà durante il processo di flashing.\n"

#: ../message.py:80
msgid "and there is made an extra copy in: "
msgstr "un'altra copia è stata creata in: "

#: ../message.py:95
msgid "available "
msgstr "disponibile "

#: ../message.py:120
msgid "backupstick or"
msgstr "backupstick oppure"

#: ../message.py:121
msgid "backupstick.txt"
msgstr "backupstick.txt"

#: ../plugin.py:266 ../plugin.py:328
#, python-format
msgid "current:  %s"
msgstr "Attuale:  %s"

#: ../message.py:195
msgid "is not executable..."
msgstr "non è eseguibile ..."

#: ../message.py:144
msgid "minutes"
msgstr "Minuti"

#: ../message.py:50
msgid "not found, the backup process will be aborted!"
msgstr "non trovato, il processo di backup sarà abortito! "

#: ../message.py:210
msgid "not installed yet, now installing"
msgstr "non ancora installata, ora la installo"

#: ../plugin.py:526
msgid "ofgwrite will stop enigma2 now to run the flash.\n"
msgstr "Il programma ofgwrite fermerà Enigma2 per iniziare il processo di flashing.\n"
