msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-07-22 19:19+0200\n"
"PO-Revision-Date: \n"
"Last-Translator: Pedro_Newbie <backupsuite@outlook.com>\n"
"Language-Team: \n"
"Language: pl\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 2.1.1\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: ../plugin.py:441
msgid ""
"\n"
"The found files:"
msgstr ""
"\n"
"Znalezione pliki:"

#: ../plugin.py:358
msgid ""
"\n"
"You are using dual multiboot!"
msgstr ""

#: ../plugin.py:447
#, python-format
msgid "  %s (maybe error)"
msgstr "  %s (być może błąd)"

#: ../plugin.py:444
#, python-format
msgid "  %s (maybe ok)"
msgstr "  %s (być może ok)"

#: ../message.py:180
msgid " MB available space"
msgstr " MB dostępnego miejsca"

#: ../message.py:185
msgid " MB needed space"
msgstr " MB potrzebne"

#: ../plugin.py:450
msgid " nothing!"
msgstr "brak!"

#: ../message.py:45
msgid " size to be backed up: "
msgstr " rozmiar do zarchiwizowania: "

#: ../message.py:175
msgid " to make a back-up!"
msgstr " aby utworzyć backup!"

#: ../message.py:169
msgid "* * * WARNING * * *"
msgstr "* * *UWAGA * * *"

#: ../plugin.py:480
msgid "A recording is currently running. Please stop the recording before trying to start a flashing."
msgstr "Aktualnie trwa nagrywanie! Zatrzymaj je zanim rozpoczniesz procedurę wgrywania image."

#: ../message.py:70
msgid "Additional backup -> "
msgstr "Dodatkowy backup -> "

#: ../message.py:35
msgid "BACK-UP TOOL, FOR MAKING A COMPLETE BACK-UP"
msgstr "NARZĘDZIE DO TWORZENIA KOMPLETNEGO BACKUPU"

#: ../plugin.py:132
msgid "Backup > HDD"
msgstr ""

#: ../plugin.py:130
msgid "Backup > MMC"
msgstr ""

#: ../plugin.py:133
msgid "Backup > USB"
msgstr ""

#: ../plugin.py:584 ../plugin.py:591
msgid "Backup and restore your image"
msgstr ""

#: ../message.py:149
msgid "Backup done with: "
msgstr "Archiwizacja odbywa się: "

#: ../message.py:106
msgid "Backup finished and copied to your USB-flashdrive."
msgstr "Backup zakończony i skopiowany na pendrive USB."

#: ../plugin.py:338 ../plugin.py:541
#, fuzzy
msgid "Backup info"
msgstr "BackupSuite"

#: ../plugin.py:583 ../plugin.py:590
msgid "BackupSuite"
msgstr "BackupSuite"

#: ../plugin.py:131 ../plugin.py:233 ../plugin.py:262
msgid "Close"
msgstr ""

#: ../message.py:65
msgid "Create: kerneldump"
msgstr "Tworzenie: kerneldump"

#: ../message.py:60
msgid "Create: root.ubifs"
msgstr "Tworzenie: root.ubifs"

#: ../plugin.py:339 ../plugin.py:570
msgid "Delete"
msgstr ""

#: ../plugin.py:567
#, fuzzy
msgid "Delete backup"
msgstr "Przywróć backup"

#: ../plugin.py:540
#, python-format
msgid "Do you really want to unpack %s ?"
msgstr "Napewno chcesz rozpakować %s ?"

#: ../plugin.py:153
msgid ""
"Do you want to make a back-up on USB?\n"
"\n"
"This only takes a few minutes depending on the used filesystem and is fully automatic.\n"
"\n"
"Make sure you first insert an USB flash drive before you select Yes."
msgstr ""
"Czy chcesz stworzyć backup na USB?\n"
"\n"
"To zajmie tylko kilka minut, w zależności od używanego filesystemu i jest w pełni automatyczne.\n"
"\n"
"Upewnij się, że podłączyłeś pendrive USB zanim wybierzesz TAK."

#: ../plugin.py:150
msgid ""
"Do you want to make an USB-back-up image on HDD? \n"
"\n"
"This only takes a few minutes and is fully automatic.\n"
msgstr ""
"Czy chcesz stworzyć backup image (w formacie usb) na HDD? \n"
"\n"
"To zajmie tylko kilka minut i jest w pełni automatyczne.\n"

#: ../plugin.py:156
#, fuzzy
msgid ""
"Do you want to make an USB-back-up image on MMC? \n"
"\n"
"This only takes a few minutes and is fully automatic.\n"
msgstr ""
"Czy chcesz stworzyć backup image (w formacie usb) na HDD? \n"
"\n"
"To zajmie tylko kilka minut i jest w pełni automatyczne.\n"

#: ../plugin.py:470
msgid "Exit"
msgstr "Wyjdź"

#: ../plugin.py:484
msgid "Flashing: "
msgstr "Wgrywanie:"

#: ../plugin.py:369
msgid "For flashing your receiver files are needed:\n"
msgstr "Pliki potrzebne do flashowania twojego odbiornika:\n"

#: ../message.py:129
msgid "Full back-up direct to USB"
msgstr "Pełny backup image bezpośrednio na USB"

#: ../plugin.py:194
msgid "Full back-up on HDD"
msgstr "Backup image na HDD"

#: ../plugin.py:208
#, fuzzy
msgid "Full back-up on MMC"
msgstr "Backup image na HDD"

#: ../plugin.py:201
msgid "Full back-up to USB"
msgstr "Backup image na USB"

#: ../message.py:235
#, fuzzy
msgid "Full back-up to the MultiMediaCard"
msgstr "Pełny backup image na dysku"

#: ../message.py:111
msgid "Full back-up to the harddisk"
msgstr "Pełny backup image na dysku"

#: ../message.py:123
msgid "If you place an USB-stick containing this file then the back-up will be automatically made onto the USB-stick and can be used to restore the current image if necessary."
msgstr "Jeśli umieścisz pendrive USB zawierający ten plik, backup zostanie automatycznie zapisany na pendrive i może być użyty w razie konieczności do przywrócenia aktualnego image."

#: ../message.py:90
msgid "Image creation FAILED!"
msgstr "Tworzenie image NIE POWIODŁO SIĘ!"

#: ../message.py:225
msgid "Installed packages contained in this backup:"
msgstr ""

#: ../message.py:154
msgid "KB per second"
msgstr "KB na sekundę"

#: ../plugin.py:127
msgid "Make a backup or restore a backup"
msgstr "Wykonaj lub przywróc kopie image"

#: ../message.py:159
msgid "Most likely this back-up can't be restored because of it's size, it's simply too big to restore. This is a limitation of the bootloader not of the back-up or the BackupSuite."
msgstr "Najprawdopodobniej ten backup nie będzie mógł zostać przywrócony ze względu na zbyt duży rozmiar. Jest to ograniczenie bootloadera, nie jest to wina backupu ani pluginu"

#: ../plugin.py:45
msgid "NAS"
msgstr ""

#: ../message.py:230
msgid "NFI Image created in: "
msgstr ""

#: ../plugin.py:516
msgid "NOT found files for flashing!\n"
msgstr "NIE znaleziono plików do flashowania!\n"

#: ../message.py:220
msgid "No additional USB-stick found to copy an extra backup"
msgstr ""

#: ../plugin.py:173 ../message.py:30
msgid "No supported receiver found!"
msgstr "Odbiornik nie wspierany przez plugin!"

#: ../message.py:170
msgid "Not enough free space on "
msgstr "Za mało wolnego miejsca na"

#: ../plugin.py:458 ../plugin.py:499
msgid "Only kernel"
msgstr "Tylko kernel"

#: ../plugin.py:457 ../plugin.py:496
msgid "Only root"
msgstr "Tylko root"

#: ../message.py:118
msgid "PLEASE READ THIS:"
msgstr "PRZECZYTAJ:"

#: ../message.py:40
msgid "Please be patient, a backup will now be made, this will take about: "
msgstr "Prosimy o cierpliwość, kopia zapasowa zostanie wykonana, to zajmie około: "

#: ../message.py:85
msgid "Please check the manual of the receiver on how to restore the image."
msgstr ""

#: ../plugin.py:234
msgid "Please wait"
msgstr ""

#: ../plugin.py:528
msgid "Please: DO NOT reboot your STB and turn off the power.\n"
msgstr "Uwaga: NIE restartuj odbiornika ani NIE wyłączaj zasilania.\n"

#: ../message.py:215
msgid "Probably you are trying to make the back-up in flash memory"
msgstr ""

#: ../plugin.py:134
msgid "Restore backup"
msgstr "Przywróć backup"

#: ../plugin.py:336 ../plugin.py:353 ../plugin.py:362
msgid "Run flash"
msgstr "Uruchom wgrywanie"

#: ../plugin.py:464 ../plugin.py:511
#, fuzzy
msgid "Second partition (only kernel)"
msgstr "Standard (root and kernel)"

#: ../plugin.py:463 ../plugin.py:508
msgid "Second partition (only root)"
msgstr ""

#: ../plugin.py:462 ../plugin.py:505
#, fuzzy
msgid "Second partition (root and kernel)"
msgstr "Standard (root and kernel)"

#: ../plugin.py:368
msgid "Select parameter for start flash!\n"
msgstr "Wybierz parametry aby rozpocząć wgrywanie!\n"

#: ../plugin.py:261
msgid "Select the folder with backup"
msgstr "Wybierz katalog z backupem"

#: ../plugin.py:521
msgid "Show only found image and mtd partitions.\n"
msgstr "Pokaż tylko znalezione image i partycje mtd.\n"

#: ../plugin.py:455 ../plugin.py:487
msgid "Simulate (no write)"
msgstr "Symulacja (bez zapisu)"

#: ../plugin.py:461 ../plugin.py:502
#, fuzzy
msgid "Simulate second partition (no write)"
msgstr "Symulacja (bez zapisu)"

#: ../message.py:55
msgid "Some information about the task"
msgstr "Niektóre informacje o zadaniu"

#: ../plugin.py:456 ../plugin.py:490
msgid "Standard (root and kernel)"
msgstr "Standard (root and kernel)"

#: ../message.py:134
msgid "The content of the folder is:"
msgstr "Zawartość folderu jest:"

#: ../plugin.py:529
msgid "The image or kernel will be flashing and auto booted in few minutes.\n"
msgstr "Image lub kernel zostanie wgrany i uruchomi się automatycznie za kilka minut.\n"

#: ../message.py:190
msgid "The program will abort, please try another medium with more free space to create your back-up."
msgstr "Wykonywanie zostanie przerwane, do utworzenia swojego backupu użyj innego nośnika, z więksżą ilością wolnego miejsca."

#: ../message.py:124
msgid "The program will exit now."
msgstr "Program zostanie teraz zamknięty."

#: ../message.py:164
msgid "There COULD be a problem with restoring this back-up because the size of the back-up comes close to the maximum size. This is a limitation of the bootloader not of the back-up or the BackupSuite."
msgstr "MOŻE wystąpić problem z przywróceniem tego backupu ponieważ jego rozmiar zbliża się do maksymalnego dopuszczalnego. Jest to ograniczenie bootloadera, nie jest to wina backupu ani pluginu"

#: ../message.py:116
msgid "There is NO valid USB-stick found, so I've got nothing to do."
msgstr "NIE znaleziono prawidłowego pendrive USB, nie można wykonać backupu."

#: ../message.py:100
msgid "There is a valid USB-flashdrive detected in one of the USB-ports, therefore an extra copy of the back-up image will now be copied to that USB-flashdrive."
msgstr "Wykryto prawidłowy pendrive USB w jednym z gniazd, w związku z tym, dodatkowa kopia backupu będzie zapisana na tym nośniku."

#: ../message.py:101
msgid "This only takes about 20 seconds....."
msgstr "To zajmie tylko 20 sekund..."

#: ../message.py:139
msgid "Time required for this process: "
msgstr "Czas potrzebny na ten proces: "

#: ../message.py:119
msgid "To back-up directly to the USB-stick, the USB-stick MUST contain a file with the name:"
msgstr "Aby stworzyć backup bezpośrednio na USB, pendrive MUSI zawierać plik o nazwie:"

#: ../message.py:75
msgid "USB Image created in: "
msgstr "Image USB utworzone na: "

#: ../plugin.py:334 ../plugin.py:537
msgid "Unzip"
msgstr "Rozpakuj zip"

#: ../message.py:200
msgid "Using your own custom lookuptable.txt from the folder /etc"
msgstr ""

#: ../message.py:205
msgid "Version unknown, probably not installed the right way."
msgstr ""

#: ../plugin.py:359
msgid ""
"Warning!\n"
"Use at your own risk! Make always a backup before use!\n"
"Don't use it if you use multiple ubi volumes in ubi layer!"
msgstr ""
"Uwaga!\n"
"Używasz na własne ryzyko! Zawsze najpierw utwórz backup!\n"
"Nie używaj jeśli używasz kilku woluminów ubi w warstwie ubi!"

#: ../plugin.py:232
msgid "What is new since the last release?"
msgstr "Co nowego od ostatniego wydania?"

#: ../plugin.py:571
#, python-format
msgid ""
"You are about to delete this backup:\n"
"\n"
"%s\n"
"Continue?"
msgstr ""

#: ../plugin.py:527
msgid "Your STB will freeze during the flashing process.\n"
msgstr "Odbiornik będzie 'zamrożony' podczas procedury wgrywania.\n"

#: ../message.py:80
msgid "and there is made an extra copy in: "
msgstr "i dodatkowa kopia utworzona na: "

#: ../message.py:95
msgid "available "
msgstr "dostępny "

#: ../message.py:120
msgid "backupstick or"
msgstr "backupstick lub"

#: ../message.py:121
msgid "backupstick.txt"
msgstr "backupstick.txt"

#: ../plugin.py:266 ../plugin.py:328
#, python-format
msgid "current:  %s"
msgstr "bieżacy:  %s"

#: ../message.py:195
msgid "is not executable..."
msgstr ""

#: ../message.py:144
msgid "minutes"
msgstr "minuty"

#: ../message.py:50
msgid "not found, the backup process will be aborted!"
msgstr ""

#: ../message.py:210
msgid "not installed yet, now installing"
msgstr ""

#: ../plugin.py:526
msgid "ofgwrite will stop enigma2 now to run the flash.\n"
msgstr "ofgwrite zastopuje teraz e2 aby uruchomić flashowanie.\n"
